### PR TITLE
Add support for custom prefixing of JSON parsed secrets

### LINKED ISSUE #11: Parsing json secrets without prefix
Hello all. Would it be possible to parse a json secret and inject the keys as environment variables raw into the environment? For our purposes this would be a cleaner solution than having to account for the variables with the added prefix. 

Thanks in advance for any and all thoughts in this regard!

### PR DESCRIPTION
**Pull request by jromero-pg**
### Summary

Add support for custom prefixing of JSON-parsed secrets.

In our particular case, we needed to disable prefixing. This was achieved by implementing custom prefixing and supporting "empty" prefixes.

### Issues Closed

Resolves #11

### Details

From the updated README:

---

**Example 4: Parsed JSON in secret with custom prefix**

The following example creates environment variables by parsing the JSON in the secret and prefixes them based on provided prefix.
​
```
- name: Get Secrets by Name and by ARN
  uses: aws-actions/aws-secretsmanager-get-secrets@v1
  with:
    secret-ids: |
      CUSTOM,test/secret
    parse-json-secrets: true
```

The secret `test/secret` has the following secret value.
​
```
{
  "api_user": "user",
  "api_key": "key",
  "config": {
    "active": "true"
  }
}
```

Environment variables created:
​
```
CUSTOM_API_USER: "user"
CUSTOM_API_KEY: "key"
CUSTOM_CONFIG_ACTIVE: "true"
```

> **Pro-tip**: It's possible remove prefixes by providing an "empty" prefix:
>
> ```
> - name: Get Secrets by Name and by ARN
>   uses: aws-actions/aws-secretsmanager-get-secrets@v1
>   with:
>     secret-ids: |
>       ,test/secret
>     parse-json-secrets: true
> ```

### CODE REVIEW

**Comment by ivanpenchev** [comment]
I would love to see this supported in the action.

**Comment by goyalya** [comment]
Thank you for submitting the request. Could you please share details on your use-case for the need of custom pre-fixing?

**Comment by jromero-pg** [comment]
There are a few reasons why this was implemented the way it is:

1. It leverages the existing syntax of aliasing.
2. It allows you to specify prefixing per secret id (as opposed to a top-level option).
3. It works well with existing auto prefixing when `parse-json-secrets=true`.

In our case, there are two cases we'd want to support:

1. We want to load a batch of env vars without the auto prefixing to the CI environment when using `parse-json-secrets=true`. Before this change, there was no way to achieve this. (see #11).
1. In specific tasks, we want to provide fallback/override values without shadowing (truly overwriting). For example, assuming there is env var `KEY_1`, during e2e tests, we want to override the env var by using a known prefix (ie. `E2E_`) and use minor logic to look up env vars by prefix or fallback to non-prefixed values. We wouldn't want to tie the implementation of this known prefix to how secrets are stored in the secrets manager.

**Comment by FalconerTC** [comment]
Any updates here? I'd really like to start using this feature

**Comment by jbct** [comment]
Hi FalconerTC - this is still something we're tracking in our backlog but unfortunately have no timelines to communicate at this time.

**Comment by zMynxx** [comment]
6 months later, any updates? 
The option to not have a prefix at all is crucial, when using jsons..

**Comment by mjmarianetti** [comment]
would like to have this supported, being able to retrieve secrets without prefix

**Comment by monim67** [comment]
Any fork that supports it? I need to get rid of unwanted prefixes.

**Comment by alankarjain05** [comment]
any update on this PR? This is a much needed feature

**Comment by zaru** [comment]
Certainly, this pull request being supported would be convenient.
For the time being, I am using the following workaround to remove the prefix:

```yaml
- name: Get secrets from AWS Secrets Manager
  id: get-aws-secret
  uses: aws-actions/aws-secretsmanager-get-secrets@v1
  with:
    secret-ids: |
      FROM_SECRETSMANAGER,fookey
    parse-json-secrets: true

- name: Remove prefix from secrets
  run: |
    for variable in "${!FROM_SECRETSMANAGER_@}"; do 
      echo "${variable#FROM_SECRETSMANAGER_}=${!variable}" >> $GITHUB_ENV
    done
```

**Pull request closed without merging**
